### ISSUE TITLE
Potential for Actor ID duplicates

### ISSUE THREAD

**Issue by morgana-x** [ncrypted-dev/Fishy#13]
In Spawner.cs the method of generating a new ID uses _random.Next();

Whilst it generates a 32 bit integer which is reasonably large and has a large number of possibilities, on the off chance that it generates a duplicate id, there will no doubt be some issues that could arise

Perhaps looping through existing actors, and finding the smallest available id would be a reasonable solution to avoid this

**Comment by morgana-x** [comment]
Well this is the dumbest solution I could think of, would take awhile to reach max value so it could be a stand-in solution perhaps
```cs
       private static int nextId = 100;
       public static int GetFreeId()
       {
           nextId++;
           if (nextId >= int.MaxValue - 1)
               nextId = 100;
           return nextId;
       }
 ```

**Comment by Kaliumhexacyanoferrat** [comment]
As multiple actors could possibly be spawned at the same time via the webserver I would synchronize this with a `volatile` int and `Interlocked.Increment` - extremely unlikely, I know, but it's only a small change there.

**Comment by morgana-x** [comment]
```cs
   private static volatile int nextId = 100;
   public static int GetFreeId()
   {
       Interlocked.Increment(ref nextId);
       if (nextId >= int.MaxValue - 1)
           nextId = 100;
       return nextId;
   }
   ```
   Like this?

**Comment by Kaliumhexacyanoferrat** [comment]
Okay, nevermind, this is more complicated than I thought. Probably stay with your original snippet 😄

```csharp
var originalValue = nextId;
var newValue = originalValue == int.MaxValue - 1 ? 100 : originalValue + 1;

return (newValue == Interlocked.CompareExchange(ref nextId, newValue, originalValue)) ? newValue : GetFreeId();
```

**Comment by ncrypted-dev** [comment]
I have implemented further checks to avoid duplicate IDs for now, but I am unsure if incremental ones with Interlocked increments like you have proposed would be better.

**Comment by Kaliumhexacyanoferrat** [comment]
I think it's fine :)
