### ISSUE TITLE
Lack of support for other languages

### ISSUE THREAD

**Issue by iNightboat** [ncrypted-dev/Fishy#3]
If you write something in the `config.toml` file in the `join_message` and `report_response` parameters that is not in English (in my case, in _Russian_), then the messages will not be displayed in the game chat.

**Comment by ncrypted-dev** [comment]
Hey, thanks for the Bug-Report - I haven't found the root cause of the issue yet, but I suspect that it has something to do with the Encoding in the GodotUtilWriter or the Padding applied after converting the String to bytes.

**Comment by iNightboat** [comment]
> Hey, thanks for the Bug-Report - I haven't found the root cause of the issue yet, but I suspect that it has something to do with the Encoding in the GodotUtilWriter or the Padding applied after converting the String to bytes.

Thanks a lot for the reply. 
Although this does not relate to the topic related to this problem, I would like to suggest adding logging to the program so that in case of an unexpected program stop, you can see exactly why it stopped

**Comment by ncrypted-dev** [comment]
> > Hey, thanks for the Bug-Report - I haven't found the root cause of the issue yet, but I suspect that it has something to do with the Encoding in the GodotUtilWriter or the Padding applied after converting the String to bytes.
> 
> Thanks a lot for the reply. Although this does not relate to the topic related to this problem, I would like to suggest adding logging to the program so that in case of an unexpected program stop, you can see exactly why it stopped

Hey, improved logging is definitely on my TODO list - Once I actually have some more time, I will implement that.
I have also been able to find the origin of your issue - Repo should contain the fix now, and I will compile and upload a new build tomorrow!
